###

GET http://localhost:4000/

###

GET http://localhost:4000/snippet/create

###

GET http://localhost:4000/snippet/view/123

###

POST http://localhost:4000/snippet/view/123
Content-Type: text/plain

ulol

###

POST http://localhost:4000/snippet/create
Content-Type: text/plain

ulol

###
